# EXAMPLE

[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
olc_version = "0.8.18"
optimizer_runs = 1_000_000

[fmt]
line_length = 80
number_underscore = "thousands"

[rpc_endpoints]
optimism = "${OPTIMISM_NODE_URL}"
optimismGoerli = "${OPTIMISM_GOERLI_NODE_URL}"

[etherscan]
optimism = { key = "${ETHERSCAN_API_KEY}" }
optimismGoerli = { key = "${ETHERSCAN_API_KEY}" }